APT::FTPArchive::Release {
  Origin "basecubedev";
  Label "basecubedev APT Repository";
  Suite "stable";
  Codename "stable";
  Architectures "amd64 arm64";
  Components "main";
  Description "basecubedev Debian/Ubuntu packages";
};
